config/routes.rb
FoodDiary::Application.routes.draw do
  resources :entries
  root :to => 'entries#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  before_validation :set_time, :copy_older, :expand_meal_time
  
  validates_presence_of :food
  validates_presence_of :amount
  
  validates_format_of :meal_time, :with => /\d?\d:\d\d(am|pm)/, :message => 'should be in the form of a time'
  validates_presence_of :location
  validates_presence_of :sensory
  validates_presence_of :emotional
  
private
  def set_time
    self.time ||= Time.now.to_date
  end
  
  def copy_older
    # time is set eariler
    older = Entry.find_last_by_time self.time
    return unless older
    
    self.meal_time = older.meal_time if self.meal_time.blank?
    self.location  = older.location if self.location.blank?
    self.sensory   = older.sensory if self.sensory.blank?
    self.emotional = older.emotional if self.emotional.blank?
  end
  
  def expand_meal_time
    return if self.meal_time.blank?
    return if self.meal_time.include? ':'
    if self.meal_time =~ /(\d)(am|pm)/
      self.meal_time = "#{$1}:00#{$2}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  include EntriesHelper
  before_filter :set_date
  
  # GET /entries
  # GET /entries.xml
  def index
    @entries = Entry.find_all_by_time(params[:date], :order => :created_at)
    @entry   ||= Entry.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entries }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.xml
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to(:action => :index, :notice => 'Entry was successfully created.') }
        format.xml  { render :xml => @entry, :status => :created, :location => @entry }
      else
        format.html do
          @entries = Entry.find_all_by_time params[:date]
          render :action => "index"
        end
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.xml
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to(:action => :index, :notice => 'Entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.xml
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to(:action => :index) }
      format.xml  { head :ok }
    end
  end
  
private
  def set_date
    params[:date] ||= todays_date
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
  def todays_date
    Time.now.to_date
  end
end

app/views/entries/_entry.html.erb
<tr>
  <td><%= entry.food.titleize %></td>
  <td><%= entry.amount %></td>
  <td><%= "#{entry.meal_time}; #{entry.location.titleize}" %></td>
  <td><%= entry.sensory.titleize %></td>
  <td><%= entry.emotional.titleize %></td>
  <td>
    <%= link_to 'Edit', edit_entry_path(entry) -%> / <%= link_to 'Delete', entry, :method => :delete %>
  </td>
</tr>

app/views/entries/_entry_row.html.erb
<tr>
  <td><%= link_to 'Show', entry %></td>
  <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
  <td><%= link_to 'Destroy', entry, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :food %>
    <%= f.text_field :food %>
  </div>
  
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>
  
  <div class="field">
    <%= f.label :meal_time %>
    <%= f.text_field :meal_time %>
  </div>
  
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  
  <div class="field">
    <%= f.label :sensory %>
    <%= f.text_field :sensory %>
  </div>
  
  <div class="field">
    <%= f.label :emotional %>
    <%= f.text_field :emotional %>
  </div>
  
  <%= f.submit %><%= link_to 'Cancel' %>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Food for <%= todays_date %></h1>

<p id="notice"><%= params[:notice] %></p>

<table class=food>
  <tr>
    <th>Food</th>
    <th>Amount</th>
    <th>Time/Place</th>
    <th>Sensory</th>
    <th>Emotional</th>
    <th>Action</th>
  </tr>
  
  <%= render :partial => 'entry', :collection => @entries %>
</table>

<br> 
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodDiary</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>